services:
    bitbag_sylius_elasticsearch_plugin.controller.action.shop.list_products:
        class: BitBag\SyliusElasticsearchPlugin\Controller\Action\Shop\ListProductsAction
        arguments:
            - "@bitbag_sylius_elasticsearch_plugin.finder.shop_products"
            - "@bitbag_sylius_elasticsearch_plugin.controller.request_data_handler.shop_product_list"

    bitbag_sylius_elasticsearch_plugin.controller.request_data_handler.shop_product_list:
        class: BitBag\SyliusElasticsearchPlugin\Controller\RequestDataHandler\ShopProductListDataHandler
        arguments:
            - "%bitbag_es_shop_name_property%"
            - "%bitbag_es_shop_taxons_property%"
            - "%bitbag_es_shop_option_property_prefix%"
            - "%bitbag_es_shop_attribute_property_prefix%"
