services:
    bitbag_sylius_elasticsearch_plugin.finder.shop_products:
        class: BitBag\SyliusElasticsearchPlugin\Finder\ShopProductsFinder
        arguments:
            - "@bitbag_sylius_elasticsearch_plugin.query_builder.shop_products"
            - "@fos_elastica.finder.bitbag_shop_product.default"
