services:
    bitbag_sylius_elasticsearch_plugin.finder.shop_products:
        class: BitBag\SyliusElasticsearchPlugin\Finder\ShopProductsFinder
        arguments:
            - "@bitbag_sylius_elasticsearch_plugin.query_builder.shop_products"
            - "@fos_elastica.finder.bitbag_shop_product.default"

    bitbag_sylius_elasticsearch_plugin.finder.options:
        class: BitBag\SyliusElasticsearchPlugin\Finder\OptionsFinder
        arguments:
            - "@fos_elastica.finder.bitbag_option_taxons.default"
            - "@bitbag_sylius_elasticsearch_plugin.query_builder.product_options_by_taxon"
            - "%bitbag_es_shop_option_taxons_property%"
