services:
    bitbag_sylius_elasticsearch_plugin.form.type.name_filter:
        class: BitBag\SyliusElasticsearchPlugin\Form\Type\NameFilterType
        tags:
            - { name: form.type }

    bitbag_sylius_elasticsearch_plugin.form.type.product_options_filter:
        class: BitBag\SyliusElasticsearchPlugin\Form\Type\ProductOptionsFilterType
        arguments:
            - "@bitbag.sylius_elasticsearch_plugin.context.product_options"
            - "@bitbag_sylius_elasticsearch_plugin.property_name_resolver.option"
        tags:
            - { name: form.type }

    bitbag_sylius_elasticsearch_plugin.form.type.product_attributes_filter:
        class: BitBag\SyliusElasticsearchPlugin\Form\Type\ProductAttributesFilterType
        arguments:
            - "@bitbag.sylius_elasticsearch_plugin.context.product_attributes"
            - "@sylius.repository.product_attribute_value"
            - "@bitbag_sylius_elasticsearch_plugin.property_name_resolver.attribute"
        tags:
            - { name: form.type }

    bitbag_sylius_elasticsearch_plugin.form.type.shop_products_filter:
        class: BitBag\SyliusElasticsearchPlugin\Form\Type\ShopProductsFilterType
        arguments:
            - "%bitbag_es_shop_name_property_prefix%"
        tags:
            - { name: form.type }
