services:
    bitbag_sylius_elasticsearch_plugin.form.type.name_filter:
        class: BitBag\SyliusElasticsearchPlugin\Form\Type\NameFilterType
        tags:
            - { name: form.type }

    bitbag_sylius_elasticsearch_plugin.form.type.options_filter:
        class: BitBag\SyliusElasticsearchPlugin\Form\Type\OptionsFilterType
        arguments:
            - "@bitbag.sylius_elasticsearch_plugin.context.product_options"
            - "%bitbag_es_shop_option_property_prefix%"
        tags:
            - { name: form.type }

    bitbag_sylius_elasticsearch_plugin.form.type.shop_products_filter:
        class: BitBag\SyliusElasticsearchPlugin\Form\Type\ShopProductsFilterType
        tags:
            - { name: form.type }
