services:
    bitbag_sylius_elasticsearch_plugin.property_builder.option:
        class: BitBag\SyliusElasticsearchPlugin\PropertyBuilder\OptionPropertyBuilder
        arguments:
           - "%bitbag_es_shop_option_property_prefix%"
        tags:
            - { name: kernel.event_subscriber }

    bitbag_sylius_elasticsearch_plugin.property_builder.attribute:
        class: BitBag\SyliusElasticsearchPlugin\PropertyBuilder\AttributePropertyBuilder
        arguments:
            - "%bitbag_es_shop_attribute_property_prefix%"
        tags:
            - { name: kernel.event_subscriber }

    bitbag_sylius_elasticsearch_plugin.property_builder.taxons:
        class: BitBag\SyliusElasticsearchPlugin\PropertyBuilder\TaxonsPropertyBuilder
        arguments:
            - "%bitbag_es_shop_product_taxons_property%"
        tags:
            - { name: kernel.event_subscriber }

    bitbag_sylius_elasticsearch_plugin.property_builder.channels:
        class: BitBag\SyliusElasticsearchPlugin\PropertyBuilder\ChannelsPropertyBuilder
        arguments:
            - "%bitbag_es_shop_channels_property%"
        tags:
            - { name: kernel.event_subscriber }

    bitbag_sylius_elasticsearch_plugin.property_builder.option_taxons:
        class: BitBag\SyliusElasticsearchPlugin\PropertyBuilder\OptionTaxonsPropertyBuilder
        arguments:
            - "@sylius.repository.product"
            - "%bitbag_es_shop_option_property_prefix%"
            - "%bitbag_es_shop_option_taxons_property%"
        tags:
            - { name: kernel.event_subscriber }
