services:
    bitbag_sylius_elasticsearch_plugin.query_builder.is_enabled:
        class: BitBag\SyliusElasticsearchPlugin\QueryBuilder\IsEnabledQueryBuilder
        arguments:
           - "%bitbag_es_shop_enabled_property%"

    bitbag_sylius_elasticsearch_plugin.query_builder.has_channel:
        class: BitBag\SyliusElasticsearchPlugin\QueryBuilder\HasChannelQueryBuilder
        arguments:
           - "@sylius.context.channel"
           - "%bitbag_es_shop_channels_property%"

    bitbag_sylius_elasticsearch_plugin.query_builder.contains_name:
        class: BitBag\SyliusElasticsearchPlugin\QueryBuilder\ContainsNameQueryBuilder
        arguments:
           - "%bitbag_es_shop_name_property%"

    bitbag_sylius_elasticsearch_plugin.query_builder.has_product_taxon:
        class: BitBag\SyliusElasticsearchPlugin\QueryBuilder\HasTaxonQueryBuilder
        arguments:
           - "%bitbag_es_shop_product_taxons_property%"

    bitbag_sylius_elasticsearch_plugin.query_builder.has_option_taxon:
        class: BitBag\SyliusElasticsearchPlugin\QueryBuilder\HasTaxonQueryBuilder
        arguments:
           - "%bitbag_es_shop_option_taxons_property%"

    bitbag_sylius_elasticsearch_plugin.query_builder.has_options:
        class: BitBag\SyliusElasticsearchPlugin\QueryBuilder\HasOptionsQueryBuilder
        arguments:
           - "%bitbag_es_shop_option_property_prefix%"

    bitbag_sylius_elasticsearch_plugin.query_builder.shop_products:
        class: BitBag\SyliusElasticsearchPlugin\QueryBuilder\ShopProductsQueryBuilder
        arguments:
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.is_enabled"
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.has_channel"
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.contains_name"
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.has_product_taxon"
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.has_options"
           - "%bitbag_es_shop_option_property_prefix%"

    bitbag_sylius_elasticsearch_plugin.query_builder.product_options_by_taxon:
        class: BitBag\SyliusElasticsearchPlugin\QueryBuilder\ProductOptionsByTaxonQueryBuilder
        arguments:
            - "@bitbag_sylius_elasticsearch_plugin.query_builder.has_option_taxon"
