imports:
    - { resource: "@BitBagSyliusElasticSearchPlugin/Resources/config/services.yml" }
    - { resource: "@BitBagSyliusElasticSearchPlugin/Resources/config/indexes/bitbag_shop.yml" }
    - { resource: "@BitBagSyliusElasticSearchPlugin/Resources/config/indexes/bitbag_option_taxons.yml" }

parameters:
    elasticsearch_host: localhost
    elasticsearch_port: 9200

fos_elastica:
    clients:
        default:
            host: "%elasticsearch_host%"
            port: "%elasticsearch_port%"
