bitbag_sylius_elasticsearch_plugin_shop_list_products:
    path: /list-products/{taxonSlug}
    defaults:
        _controller: bitbag_sylius_elasticsearch_plugin.controller.action.shop.list_products
        template: "@BitBagSyliusElasticSearchPlugin/Shop/Product/index.html.twig"
