imports:
    - { resource: "@BitBagSyliusElasticSearchPlugin/Resources/config/services/property_builder.yml" }
    - { resource: "@BitBagSyliusElasticSearchPlugin/Resources/config/services/property_name_resolver.yml" }
    - { resource: "@BitBagSyliusElasticSearchPlugin/Resources/config/services/query_builder.yml" }
    - { resource: "@BitBagSyliusElasticSearchPlugin/Resources/config/services/controller.yml" }
    - { resource: "@BitBagSyliusElasticSearchPlugin/Resources/config/services/finder.yml" }
    - { resource: "@BitBagSyliusElasticSearchPlugin/Resources/config/services/form.yml" }
    - { resource: "@BitBagSyliusElasticSearchPlugin/Resources/config/services/context.yml" }

services:
    bitbag.sylius_elasticsearch_plugin.string_formatter:
        class: BitBag\SyliusElasticsearchPlugin\Formatter\StringFormatter

    bitbag.sylius_elasticsearch_plugin.twig.extension.unset_array_elements:
        class: BitBag\SyliusElasticsearchPlugin\Twig\Extension\UnsetArrayElementsExtension
        tags:
            - { name: twig.extension }
