fos_elastica:
    indexes:
        bitbag_taxon:
            index_name: "bitbag_taxon_%kernel.environment%"
            types:
                product:
                    persistence:
                        driver: orm
                        model: "%sylius.model.product_option_value.class%"
                        listener:
                            defer: true
                            logger: true
                        elastica_to_model_transformer:
                            ignore_missing: true
