parameters:
    bitbag_es_shop_product_taxons_property: product_taxons

fos_elastica:
    indexes:
        bitbag_option_taxons:
            index_name: "bitbag_%kernel.environment%"
            types:
                default:
                    properties:
                        code: ~
                    persistence:
                        driver: orm
                        model: "%sylius.model.product_option.class%"
                        listener:
                            defer: true
                            logger: true
                        elastica_to_model_transformer:
                            ignore_missing: true
